"""Dominant transmission chains — the 25 highest-energy causal paths.

Ranked by historical explanatory power from MACRO_FACTOR_REPORT.md.
Each chain is an ordered list of node IDs representing the primary transmission
path, with tier (1-4), lag profile, and description.
"""

DOMINANT_CHAINS = [
    # ── Tier 1: Primary Transmission Chains (fire in every cycle) ──────────
    {
        "id": "rate_transmission",
        "name": "The Rate Transmission Chain",
        "tier": 1,
        "nodes": ["fed_funds_rate", "us_10y_yield", "mortgage_rate", "housing_starts", "us_gdp_growth"],
        "lag_profile": "days → days-weeks → weeks-months → months",
        "end_to_end_lag": "12-18 months",
        "description": "Textbook monetary policy mechanism. Active in every tightening cycle. Responsible for the 2022-23 housing freeze.",
    },
    {
        "id": "inflation_discount_rate",
        "name": "Inflation → Policy → Discount Rate",
        "tier": 1,
        "nodes": ["us_cpi_yoy", "fed_funds_rate", "us_real_yield", "nasdaq", "bitcoin", "gold"],
        "lag_profile": "weeks-months → days → hours-days (all repriced simultaneously)",
        "end_to_end_lag": "3-12 months",
        "description": "The unified 2022 trade. Everything long-duration fell together because it was all one chain.",
    },
    {
        "id": "dollar_wrecking_ball",
        "name": "The Dollar Wrecking Ball",
        "tier": 1,
        "nodes": ["fed_funds_rate", "dxy_index", "em_fx_basket", "em_sovereign_spread", "em_equities"],
        "lag_profile": "days → hours-days → hours-days → days (self-reinforcing)",
        "end_to_end_lag": "days-weeks",
        "description": "Why EM crises are self-reinforcing. Active in 1982, 1994, 1997, 2013, 2018, 2022.",
    },
    {
        "id": "volatility_cascade",
        "name": "The Volatility Cascade",
        "tier": 1,
        "nodes": ["vix", "margin_debt", "sp500", "vix"],
        "lag_profile": "hours → hours → hours (feedback loop)",
        "end_to_end_lag": "hours-days",
        "description": "The mechanism that turns corrections into crashes. Feb 2018, Aug 2024, every flash crash.",
    },
    {
        "id": "financial_plumbing",
        "name": "The Financial Plumbing Chain",
        "tier": 1,
        "nodes": ["bank_reserves", "repo_sofr_rate", "ted_spread", "financial_conditions_index", "sp500"],
        "lag_profile": "hours → hours → hours-days → days",
        "end_to_end_lag": "hours-days",
        "description": "When plumbing breaks, everything breaks. 2008, 2019 repo, 2020 COVID, 2023 SVB.",
    },
    # ── Tier 2: High-Frequency Chains (fire in most cycles) ────────────────
    {
        "id": "credit_accelerator",
        "name": "The Credit Accelerator",
        "tier": 2,
        "nodes": ["hy_credit_spread", "financial_conditions_index", "us_gdp_growth", "hy_credit_spread"],
        "lag_profile": "days → weeks-months → months (self-reinforcing in crisis)",
        "end_to_end_lag": "months",
        "description": "The financial accelerator. Amplifies in crises, dampens in expansions.",
    },
    {
        "id": "fiscal_doom_loop",
        "name": "The Fiscal Doom Loop",
        "tier": 2,
        "nodes": ["us_fiscal_deficit", "treasury_issuance", "us_10y_yield", "us_fiscal_deficit"],
        "lag_profile": "weeks → days → quarters (self-reinforcing)",
        "end_to_end_lag": "quarters",
        "description": "The structural risk of the 2020s decade. Drove the 2023 bond selloff.",
    },
    {
        "id": "china_global_growth",
        "name": "China → Global Growth → Commodities",
        "tier": 2,
        "nodes": ["pboc_policy", "china_credit_impulse", "china_property", "iron_ore", "copper", "global_trade_volume"],
        "lag_profile": "weeks-months → months → days-weeks → days → weeks",
        "end_to_end_lag": "6-9 months",
        "description": "China credit impulse today predicts global industrial production 6 months from now.",
    },
    {
        "id": "geopolitical_inflation",
        "name": "Geopolitics → Supply → Inflation",
        "tier": 2,
        "nodes": ["geopolitical_risk_index", "wti_crude", "natural_gas", "us_cpi_yoy", "fed_funds_rate"],
        "lag_profile": "hours → hours-days → weeks-months → weeks-months",
        "end_to_end_lag": "weeks-months",
        "description": "Russia-Ukraine, Red Sea, Iran — all follow this pattern.",
    },
    {
        "id": "housing_wealth_effect",
        "name": "The Housing Wealth Effect Chain",
        "tier": 2,
        "nodes": ["mortgage_rate", "home_prices", "consumer_confidence", "us_gdp_growth"],
        "lag_profile": "months → weeks → months",
        "end_to_end_lag": "months-quarters",
        "description": "Housing affects the economy through wealth effects AND inflation simultaneously.",
    },
    # ── Tier 3: Crisis-Specific Chains ─────────────────────────────────────
    {
        "id": "em_contagion_doom_loop",
        "name": "The EM Contagion Doom Loop",
        "tier": 3,
        "nodes": ["em_fx_basket", "em_sovereign_spread", "fund_flows", "em_fx_basket"],
        "lag_profile": "hours-days → days → days (self-reinforcing)",
        "end_to_end_lag": "days-weeks",
        "description": "Currency weakness → higher debt service → wider spreads → capital flight → more weakness.",
    },
    {
        "id": "bank_run_chain",
        "name": "The Bank Run Chain",
        "tier": 3,
        "nodes": ["regional_banks", "mmf_flows", "bank_reserves", "bank_lending_standards", "us_gdp_growth"],
        "lag_profile": "hours-days → days → weeks → months",
        "end_to_end_lag": "hours-months",
        "description": "SVB 2023. The social-media-accelerated variant executes in hours.",
    },
    {
        "id": "carry_trade_unwind",
        "name": "The Carry Trade Unwind Chain",
        "tier": 3,
        "nodes": ["japan_boj_policy", "usdjpy", "fx_volatility", "vix", "sp500"],
        "lag_profile": "hours → hours → hours → hours",
        "end_to_end_lag": "hours",
        "description": "August 5, 2024. Transmission from Tokyo to New York in a single trading session.",
    },
    {
        "id": "oil_yield_suppression_gold",
        "name": "Oil → Yield Suppression → Gold",
        "tier": 3,
        "nodes": ["wti_crude", "us_cpi_yoy", "us_10y_yield", "us_real_yield", "gold"],
        "lag_profile": "hours-days → days → hours-days → hours-days",
        "end_to_end_lag": "days-weeks",
        "description": "Counter-intuitive: geopolitical risk suppresses gold through yields. March 2026.",
    },
    {
        "id": "fiscal_trap_forced_easing",
        "name": "The Fiscal Trap → Forced Easing Chain",
        "tier": 3,
        "nodes": ["us_debt_to_gdp", "rate_expectations", "fed_funds_rate", "dxy_index", "gold"],
        "lag_profile": "weeks-months → months-quarters → days → hours-days",
        "end_to_end_lag": "quarters",
        "description": "When markets conclude rates MUST come down because the debt load leaves no choice.",
    },
    # ── Tier 4: Structural/Secular Chains ──────────────────────────────────
    {
        "id": "productivity_valuation",
        "name": "The Productivity → Valuation Chain",
        "tier": 4,
        "nodes": ["us_productivity", "earnings_momentum", "pe_valuations", "sp500"],
        "lag_profile": "quarters → days → hours",
        "end_to_end_lag": "quarters-years",
        "description": "The AI productivity question. If it's real, it justifies everything. If not, it's a bubble.",
    },
    {
        "id": "supply_chain_inflation_tightening",
        "name": "Supply Chain → Inflation → Tightening",
        "tier": 4,
        "nodes": ["supply_chain_pressure", "us_cpi_yoy", "fed_funds_rate", "us_gdp_growth"],
        "lag_profile": "weeks-months → weeks-months → months",
        "end_to_end_lag": "months",
        "description": "The 2021-22 playbook. Supply-driven inflation is harder to fight.",
    },
    {
        "id": "cre_bank_solvency",
        "name": "The CRE → Bank Solvency Chain",
        "tier": 4,
        "nodes": ["us_10y_yield", "cre_stress", "regional_banks", "bank_lending_standards", "us_gdp_growth"],
        "lag_profile": "months → weeks-months → days-weeks → months",
        "end_to_end_lag": "months-quarters",
        "description": "The slow-motion crisis. Office vacancy >20%, $1.5T in maturing CRE loans.",
    },
    {
        "id": "trade_war_chain",
        "name": "The Trade War Chain",
        "tier": 4,
        "nodes": ["trade_policy_tariffs", "supply_chain_pressure", "us_cpi_yoy", "us_pmi"],
        "lag_profile": "weeks → months → weeks-months",
        "end_to_end_lag": "weeks-months",
        "description": "Tariffs are simultaneously inflationary and growth-destructive — worst policy dilemma.",
    },
    {
        "id": "safe_haven_rotation",
        "name": "The Safe-Haven Rotation Chain",
        "tier": 4,
        "nodes": ["vix", "gold", "us_10y_yield", "dxy_index"],
        "lag_profile": "hours → hours → hours",
        "end_to_end_lag": "hours",
        "description": "The immediate response to any geopolitical or systemic shock.",
    },
    {
        "id": "leverage_cascade",
        "name": "The Leverage Cascade Chain",
        "tier": 4,
        "nodes": ["sp500", "margin_debt", "sp500", "hy_credit_spread", "bank_lending_standards"],
        "lag_profile": "hours → hours-days → hours → days",
        "end_to_end_lag": "hours-days",
        "description": "Why leveraged corrections become liquidity crises.",
    },
    {
        "id": "qe_qt_liquidity",
        "name": "The QE/QT Liquidity Chain",
        "tier": 4,
        "nodes": ["fed_balance_sheet", "bank_reserves", "financial_conditions_index", "sp500", "hy_credit_spread"],
        "lag_profile": "days → days → weeks → days",
        "end_to_end_lag": "days-weeks",
        "description": "The liquidity tide. When all four major CBs expand, risk assets have a tailwind.",
    },
    {
        "id": "earnings_equity",
        "name": "The Earnings → Equity Chain",
        "tier": 4,
        "nodes": ["revenue_growth", "earnings_momentum", "sp500", "pe_valuations", "fund_flows"],
        "lag_profile": "weeks → hours-days → hours → days",
        "end_to_end_lag": "weeks-months",
        "description": "The fundamental equity chain. Drives the bull market between crises.",
    },
    {
        "id": "crypto_contagion",
        "name": "The Crypto Contagion Chain",
        "tier": 4,
        "nodes": ["bitcoin", "margin_debt", "private_credit", "regional_banks", "bank_lending_standards"],
        "lag_profile": "hours → days → days-weeks → weeks",
        "end_to_end_lag": "days-weeks",
        "description": "Proven in 2022-23. Crypto connects to traditional finance through banks and lending.",
    },
    {
        "id": "peripheral_sovereign",
        "name": "The Peripheral Sovereign Chain",
        "tier": 4,
        "nodes": ["eu_periphery_spreads", "eurusd", "fx_volatility", "vix", "ecb_policy_rate"],
        "lag_profile": "hours-days → hours → hours-days → days → weeks",
        "end_to_end_lag": "days-weeks",
        "description": "2011-12 crisis, 2022 TPI invention. The existential risk for the Euro.",
    },
]
